base_url = "https://eudald.gr"
title = "El web de l'Eudald"
description = "Aquest és el meu web."
build_search_index = true
generate_feeds = true
compile_sass = true
minify_html = true
taxonomies = [{ name = "tags" }]
theme = "apollo"

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[markdown]
external_links_target_blank = true

[markdown.highlighting]
style = "class"
light_theme = "github-light"
dark_theme = "github-dark"
error_on_missing_language = true

[extra]
toc = true
use_cdn = false
favicon = "/icons/favicon.ico"
theme = "toggle-auto" # light, dark, auto, toggle, toggle-auto
fancy_code = true
dynamic_note = true # a note that can be toggled
mathjax = true
repo_url = "https://github.com/eudaldgr/eudald.gr"

fediverse = false    # author attribution
fediverse_creator = ""    # e.g. @user@instance

menu = [
  { name = "/posts", url = "/posts", weight = 1 },
  { name = "/projectes", url = "/projects", weight = 2 },
  { name = "/pull-requests", url = "/pull-requests", weight = 3 },
  { name = "/tags", url = "/tags", weight = 4 },
]

socials = [
  { name = "github", url = "https://github.com/eudaldgr/", icon = "github" },
  { name = "linkedin", url = "https://www.linkedin.com/in/eudaldgr/", icon = "linkedin" },
]

[extra.taxonomies]
sort_by = "page_count"
reverse = true

[extra.analytics]
enabled = false
